apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-deployment
  namespace: lfx-mentorship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - image: antrea/toolbox:1.6
        imagePullPolicy: IfNotPresent
        name: toolbox
